#
# Makefile for multifunction miscellaneous devices
#

obj-$(CONFIG_MFD_CORE)		+= mfd-core.o

obj-$(CONFIG_MFD_RK808)		+= rk808.o
obj-$(CONFIG_MFD_SYSCON)	+= syscon.o
obj-$(CONFIG_FUSB_30X)		+= fusb302.o
obj-$(CONFIG_MFD_RK1000)	+= rk1000-core.o
